[package]
name = "juno_derive"
version = "0.1.0"
authors = ["discosultan <jaanusvarus@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5"
syn = { version = "1", features = [] }
quote = "1"
